'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {getRequests} from '@/lib/data';
import type {RequestItem} from '@/lib/types';
export default function Dashboard(){
 const [requests,setRequests]=useState<RequestItem[]>([]);
 useEffect(()=>{getRequests().then(setRequests)},[]);
 const counts=useMemo(()=>({pending:requests.filter(r=>r.status==='Pending').length,progress:requests.filter(r=>r.status==='In Progress').length,completed:requests.filter(r=>r.status==='Completed').length,total:requests.length}),[requests]);
 const divisions=useMemo(()=>Object.entries(requests.reduce<Record<string,number>>((a,r)=>(a[r.division]=(a[r.division]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]).slice(0,6),[requests]);
 return <main className="container"><div className="pageTitle"><div><h2>ICT Request Monitoring Dashboard</h2><p>Monitor ICT service requests and queue status.</p></div><Link className="btn btnGold" href="/request">+ New ICT Request</Link></div><div className="grid4"><div className="stat"><div className="label">TOTAL REQUESTS</div><div className="value">{counts.total}</div><div className="hint">All submitted requests</div></div><div className="stat"><div className="label">PENDING</div><div className="value">{counts.pending}</div><div className="hint">Waiting for ICT action</div></div><div className="stat"><div className="label">IN PROGRESS</div><div className="value">{counts.progress}</div><div className="hint">Currently handled</div></div><div className="stat"><div className="label">COMPLETED</div><div className="value">{counts.completed}</div><div className="hint">Resolved requests</div></div></div><div className="sectionGrid"><section className="card"><h3>Recent ICT Requests</h3>{requests.length?<div className="tableWrap"><table className="table"><thead><tr><th>Request No.</th><th>Client</th><th>Division</th><th>Service</th><th>Status</th></tr></thead><tbody>{requests.slice(0,7).map(r=><tr key={r.id}><td><b>{r.id}</b></td><td>{r.name}</td><td>{r.division}</td><td>{r.services.join(', ')}</td><td><span className={'badge '+r.status.toLowerCase().replace(' ','')}>{r.status}</span></td></tr>)}</tbody></table></div>:<div className="empty">No requests yet. Create the first ICT service request.</div>}</section><section className="card"><h3>Requests by Division / Section</h3>{divisions.length?divisions.map(([d,n])=><div key={d} style={{marginBottom:14}}><div style={{display:'flex',justifyContent:'space-between',fontSize:13,marginBottom:5}}><span>{d}</span><b>{n}</b></div><div className="bar"><i style={{width:`${Math.max(8,n/Math.max(...divisions.map(x=>x[1]))*100)}%`}}/></div></div>):<div className="empty">Division activity will appear here.</div>}<Link href="/queue" className="btn btnLight">View full queue →</Link></section></div></main>
}
